/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 clownfish.glb
Author: zixisun02 (https://sketchfab.com/zixisun51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/clownfish-47ba2679d91a4f14b3fc0bf8e3805af5
Title: Clownfish
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Clownfish(props) {
  const { nodes, materials } = useGLTF("/clownfish.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.wire_028149177}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/clownfish.glb");
