/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 eastern_box_turtle.glb 
Author: RISD Nature Lab (https://sketchfab.com/RISDNaturelab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eastern-box-turtle-a6cb1a3f3e2d4087af82c45c91db4135
Title: Eastern Box Turtle
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BoxTurtle(props) {
  const { nodes, materials } = useGLTF("/eastern_box_turtle.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/eastern_box_turtle.glb");
