/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 humpback_whale.glb 
Author: CARI'MAM (https://sketchfab.com/CARIMAM)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/humpback-whale-f85fe853de6b4ff4a0bb3cfed2bc14a4
Title: Humpback whale
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Hwhale(props) {
  const { nodes, materials } = useGLTF("/humpback_whale.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={285.714}>
        <mesh
          geometry={nodes.polySurface1_lambert1_0.geometry}
          material={materials.lambert1}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/humpback_whale.glb");
