/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 orca.glb 
Author: Cenker Turhan (https://sketchfab.com/cenkerturhan1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/orca-db32f6164828462eaf8d3fe87c0aad85
Title: ORCA
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Orca(props) {
  const { nodes, materials } = useGLTF("/orca.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BODY_LOW_BODY_LOW_0.geometry}
        material={materials.BODY_LOW}
      />
      <mesh
        geometry={nodes.EYES_LOW_EYES_LOW_0.geometry}
        material={materials.EYES_LOW}
      />
    </group>
  );
}

useGLTF.preload("/orca.glb");
