/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 segozancia_sp_male_crab_-_instalod.glb 
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/segozancia-sp-male-crab-instalod-8416d4ef3ac84feaa5db13694e857367
Title: Segozancia Sp Male Crab - InstaLOD
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Crab(props) {
  const { nodes, materials } = useGLTF(
    "/segozancia_sp_male_crab_-_instalod.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group
        position={[14.248, -15.489, 1.552]}
        rotation={[-1.589, -0.018, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material_5}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_1}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_6}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.material_7}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.material_8}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.material_9}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/segozancia_sp_male_crab_-_instalod.glb");
