/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 tiger_shark.glb 
Author: cebraVFX (https://sketchfab.com/intervirtual)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tiger-shark-8a19770317984b4a9628934acd587a67
Title: Tiger Shark
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shark(props) {
  const { nodes, materials } = useGLTF("/tiger_shark.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[9.552, 29.562, 70.166]} rotation={[0, 1.255, 0]}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.material}
          position={[0, 0, -0.913]}
        />
      </group>
      <group
        position={[-9.552, 29.562, 70.166]}
        rotation={[-Math.PI, 1.255, 0]}
        scale={-1}
      >
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material}
          position={[0, 0, -0.913]}
        />
      </group>
      <group position={[0.003, 22.918, 67.158]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[7.069, 1.763, 0.396]}>
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.Tooth}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.Tooth}
          />
        </group>
      </group>
      <group position={[0.011, 26.705, 67.693]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[6.13, 4.215, 0.636]}>
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.Tooth}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.Tooth}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.Tooth}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials["02_-_Default"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/tiger_shark.glb");
